# Generated by Django 5.0.6 on 2024-06-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='extension',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
