# Generated by Django 5.0.6 on 2024-06-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0002_object_extension_alter_object_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
