# Generated by Django 5.0.6 on 2024-06-30 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0003_alter_object_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='extension',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('name', 'owner')},
        ),
    ]
