# Generated by Django 5.0.6 on 2024-06-30 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0004_alter_object_extension_alter_object_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='object',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='object',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_name_per_owner'),
        ),
    ]
